fix(build): use toLatin1 method instead of toAscii for QString
Can't build with QT5 and portName.toAscii():

  src/PortLatency_linux.cpp:46:28: error: 'class QString' has no member
  named 'toAscii'

Some info about toAscii() from QT4 documentation:

  If a codec has been set using QTextCodec::setCodecForCStrings(), it is
  used to convert Unicode to 8-bit char; otherwise this function does the
  same as toLatin1().

Replacing it by toLatin1() helps, toAscii seems not to be in QT5 anymore.

Signed-off-by: Youenn Piolet <piolet.y@gmail.com>